### ISSUE TITLE
Edit Column Headers

### ISSUE THREAD

**Issue by dinherfare** [adayim/forestploter#8]
Hello;

I'm trying to use the edit_plot function to edit the column headers, but I'm having trouble getting it to work.  Is there a way to change the justification of the column headers?

`
g <- edit_plot(g,
               col = c(3,5),
               part = "header",
               which = "text",
               gp = gpar(fontface = "italic", just= "left"))`

**Comment by adayim** [comment]
Sadly there's no way to edit the justifcation of the text. The code you have is wrong, check the `gpar` help file. I would suggest leave the header of that cell blank, and insert text later.

**Comment by Ling707** [comment]
Hello, I have a similar issue and I finally fixed it. I was trying to align the numbers right. I fixed this by using monospaced fonts and adding spaces to the left of the strings to make the lengths are the same. The font I used is not in HersheySerif family and there were a lot of warnings, but the font looked right to my plot. The only thing is that the space was still half the width of the numbers/letters. I fixed this by tweaking the number of spaces manually so that all the string widths are the same.

**Comment by adayim** [comment]
You can justify text at plotting stage by changing theme but not after. You can change justification for any cells in the forestplot. 

Please see here how to do that:
https://github.com/adayim/forestploter/issues/10#issuecomment-1149810452
